---
- name: OS Initialization and Configuration
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  vars:
    project_root: "{{ playbook_dir }}"
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
  pre_tasks:
    - name: Validate supported platform
      fail:
        msg: "Unsupported platform: {{ ansible_os_family }}/{{ ansible_distribution }}"
      when: >
        not (
          (ansible_os_family == 'Darwin') or
          (ansible_distribution in ['Ubuntu', 'Debian', 'Pop!_OS', 'Alpine'])
        )
    
    - name: Set platform facts
      set_fact:
        os_family: "{{ 'macos' if ansible_os_family == 'Darwin' else 'linux' }}"
        os_distribution: "{{ ansible_distribution | lower }}"
        package_manager: >-
          {%- if ansible_os_family == 'Darwin' -%}
            brew
          {%- elif ansible_distribution in ['Ubuntu', 'Debian', 'Pop!_OS'] -%}
            apt
          {%- elif ansible_distribution == 'Alpine' -%}
            apk
          {%- else -%}
            unknown
          {%- endif -%}
    
    - name: Display detected platform
      debug:
        msg: "Detected platform: {{ os_family }}/{{ os_distribution }} with {{ package_manager }} package manager"
    
  tasks:
    - name: Include main orchestration playbook
      include_tasks: playbooks/main.yml
      
  post_tasks:
    - name: Display completion message
      debug:
        msg: "System configuration completed successfully. Please restart your terminal or run 'exec $SHELL' to activate shell changes."
      
  handlers:
    - name: Restart shell
      debug:
        msg: "Shell configuration updated. Please restart your terminal or run 'exec $SHELL'" 